export enum ERouteTable {
  ROOT = '/',
  SIGIN_IN = '/sign-in',
  SIGIN_UP = '/sign-up',
  VERIFY_ACCOUNT = '/verify-account',
  FORGOT_PASSWORD = '/forgot-password',
  CHANGE_PASSWORD = '/change-password',
  HOME = '/home',
  ONBOARDING = '/onboarding',
  DETAIL_LESSON = '/detail-lesson',
  QUESTION_SCREEN = '/question-screen',
  SETTING_SCREEN = '/settings',
  LEARN_CHESS = '/learn-chess',
  ABOUT_US = '/about-us',
  EDIT_NAME = '/edit-name',
  RESET_PASSWORD = '/reset-password',
  SUPPORT = '/support',
  PRACTICE_CHESS = '/practice-chess',
  PRACTICE_CHILDREN = '/practice-children',
  QUIZ_START = '/quiz-start',
  SITUATION_SCREEN = '/situation-screen',
  STORY_SCREEN = '/(situation)/story-screen',
  FILL_VALUE_SCREEN = '/(situation)/fill-value-screen',
  RESULT_SITUATION = '/(situation)/result-situation',
  PLAY_SITUATION = '/(tabs)/play-situation',
  // New Math Games
  MEMORY_MATH_SCREEN = '/(situation)/memory-math-screen',
  SPEED_CALC_SCREEN = '/(situation)/speed-calc-screen',
  NUMBER_SEQUENCE_SCREEN = '/(situation)/number-sequence-screen',
}
